# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/dto/context.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/dto/context.proto", :syntax => :proto3) do
    add_message "io.growing.tunnel.protocol.ContextDto" do
      optional :app, :message, 1, "io.growing.tunnel.protocol.AppDto"
      optional :device, :message, 2, "io.growing.tunnel.protocol.DeviceDto"
      optional :screen, :message, 3, "io.growing.tunnel.protocol.ScreenDto"
      optional :operationSystem, :message, 4, "io.growing.tunnel.protocol.OperationSystemDto"
      optional :page, :message, 5, "io.growing.tunnel.protocol.PageDto"
      optional :referrer, :message, 6, "io.growing.tunnel.protocol.ReferrerDto"
      optional :location, :message, 7, "io.growing.tunnel.protocol.LocationDto"
      optional :network, :message, 8, "io.growing.tunnel.protocol.NetworkDto"
      optional :locale, :message, 9, "io.growing.tunnel.protocol.LocaleDto"
    end
    add_message "io.growing.tunnel.protocol.AppDto" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :package, :string, 3
      optional :version, :string, 4
      optional :url_schema, :string, 5
      optional :user_agent, :string, 6
      optional :channel, :string, 7
    end
    add_message "io.growing.tunnel.protocol.DeviceDto" do
      optional :brand, :string, 1
      optional :model, :string, 2
      optional :platform, :string, 3
      optional :type, :message, 4, "google.protobuf.Int32Value"
    end
    add_message "io.growing.tunnel.protocol.ScreenDto" do
      optional :width, :int32, 1
      optional :height, :int32, 2
      optional :density, :int32, 3
      optional :orientation, :enum, 4, "io.growing.tunnel.protocol.ScreenDto.Orientation"
    end
    add_enum "io.growing.tunnel.protocol.ScreenDto.Orientation" do
      value :PORTRAIT, 0
      value :LANDSCAPE, 1
    end
    add_message "io.growing.tunnel.protocol.OperationSystemDto" do
      optional :name, :string, 1
      optional :version, :string, 2
    end
    add_message "io.growing.tunnel.protocol.PageDto" do
      optional :domain, :string, 1
      optional :path, :string, 2
      optional :query, :string, 3
      optional :title, :string, 4
    end
    add_message "io.growing.tunnel.protocol.ReferrerDto" do
      optional :from, :string, 1
      optional :page, :string, 2
    end
    add_message "io.growing.tunnel.protocol.LocationDto" do
      optional :longitude, :double, 1
      optional :latitude, :double, 2
    end
    add_message "io.growing.tunnel.protocol.NetworkDto" do
      optional :type, :string, 1
      optional :carrier, :string, 2
    end
    add_message "io.growing.tunnel.protocol.LocaleDto" do
      optional :language, :string, 1
      optional :timezone, :string, 2
    end
  end
end

module Io
  module Growing
    module Tunnel
      module Protocol
        ContextDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.ContextDto").msgclass
        AppDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.AppDto").msgclass
        DeviceDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.DeviceDto").msgclass
        ScreenDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.ScreenDto").msgclass
        ScreenDto::Orientation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.ScreenDto.Orientation").enummodule
        OperationSystemDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.OperationSystemDto").msgclass
        PageDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.PageDto").msgclass
        ReferrerDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.ReferrerDto").msgclass
        LocationDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.LocationDto").msgclass
        NetworkDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.NetworkDto").msgclass
        LocaleDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.LocaleDto").msgclass
      end
    end
  end
end
