# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/dto/event.proto

require 'google/protobuf'

require 'v1/dto/context_pb'
require 'v1/dto/item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/dto/event.proto", :syntax => :proto3) do
    add_message "io.growing.tunnel.protocol.EventDto" do
      optional :anonymous_id, :string, 1
      optional :project_key, :string, 2
      optional :user_id, :string, 3
      optional :gio_id, :string, 4
      optional :timestamp, :int64, 5
      optional :esid, :int32, 6
      optional :session, :string, 7
      optional :event_key, :string, 8
      optional :type, :enum, 9, "io.growing.tunnel.protocol.EventDto.EventType"
      optional :version, :string, 10
      optional :ip, :string, 11
      optional :context, :message, 12, "io.growing.tunnel.protocol.ContextDto"
      map :attributes, :string, :string, 13
      optional :send_time, :int64, 14
      optional :event_num, :double, 15
      optional :data_source_id, :string, 16
      optional :item, :message, 17, "io.growing.tunnel.protocol.ItemDto"
    end
    add_enum "io.growing.tunnel.protocol.EventDto.EventType" do
      value :VISIT, 0
      value :CUSTOM_EVENT, 1
      value :PAGE, 2
      value :VISIT_CLOSE, 3
    end
    add_message "io.growing.tunnel.protocol.EventList" do
      repeated :values, :message, 1, "io.growing.tunnel.protocol.EventDto"
    end
  end
end

module Io
  module Growing
    module Tunnel
      module Protocol
        EventDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.EventDto").msgclass
        EventDto::EventType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.EventDto.EventType").enummodule
        EventList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.EventList").msgclass
      end
    end
  end
end
