# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/dto/item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/dto/item.proto", :syntax => :proto3) do
    add_message "io.growing.tunnel.protocol.ItemDto" do
      optional :id, :string, 1
      optional :key, :string, 2
      map :attributes, :string, :string, 3
      optional :data_source_id, :string, 4
      optional :project_key, :string, 5
    end
    add_message "io.growing.tunnel.protocol.ItemDtoList" do
      repeated :values, :message, 2, "io.growing.tunnel.protocol.ItemDto"
    end
  end
end

module Io
  module Growing
    module Tunnel
      module Protocol
        ItemDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.ItemDto").msgclass
        ItemDtoList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.ItemDtoList").msgclass
      end
    end
  end
end
