# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/dto/user.proto

require 'google/protobuf'

require 'growing/ruby/sdk/pb/v1/dto/user_profile_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/dto/user.proto", :syntax => :proto3) do
    add_message "io.growing.tunnel.protocol.UserDto" do
      optional :anonymous_id, :string, 1
      optional :project_key, :string, 2
      optional :user_id, :string, 3
      optional :gio_id, :string, 4
      optional :timestamp, :int64, 5
      optional :esid, :int32, 6
      optional :session, :string, 7
      optional :profile, :message, 8, "io.growing.tunnel.protocol.UserProfileDto"
      map :attributes, :string, :string, 9
      optional :send_time, :int64, 10
      optional :data_source_id, :string, 11
    end
    add_message "io.growing.tunnel.protocol.UserList" do
      repeated :values, :message, 1, "io.growing.tunnel.protocol.UserDto"
    end
  end
end

module Io
  module Growing
    module Tunnel
      module Protocol
        UserDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.UserDto").msgclass
        UserList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.UserList").msgclass
      end
    end
  end
end
