# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/dto/user_profile.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/dto/user_profile.proto", :syntax => :proto3) do
    add_message "io.growing.tunnel.protocol.UserProfileDto" do
      optional :basic, :message, 1, "io.growing.tunnel.protocol.BasicProfileDto"
      optional :device, :message, 2, "io.growing.tunnel.protocol.DeviceProfileDto"
      optional :wechat, :message, 3, "io.growing.tunnel.protocol.WechatProfileDto"
      optional :alipay, :message, 4, "io.growing.tunnel.protocol.AliPayProfileDto"
    end
    add_message "io.growing.tunnel.protocol.BasicProfileDto" do
      optional :name, :string, 1
      optional :createdAt, :message, 2, "google.protobuf.Timestamp"
      optional :birthday, :message, 3, "google.protobuf.Timestamp"
      optional :mobile, :string, 4
      optional :email, :string, 5
      optional :gender, :enum, 6, "io.growing.tunnel.protocol.BasicProfileDto.Gender"
      repeated :addresses, :string, 7
    end
    add_enum "io.growing.tunnel.protocol.BasicProfileDto.Gender" do
      value :UNKNOWN, 0
      value :FEMALE, 1
      value :MALE, 2
    end
    add_message "io.growing.tunnel.protocol.DeviceProfileDto" do
      optional :android_id, :string, 1
      optional :idfa, :string, 2
      optional :idfv, :string, 3
      optional :imei, :string, 4
    end
    add_message "io.growing.tunnel.protocol.WechatProfileDto" do
      optional :open_id, :string, 1
      optional :union_id, :string, 2
      optional :nick_name, :string, 3
      optional :avatar_url, :string, 4
      optional :gender, :string, 5
      optional :country, :string, 6
      optional :province, :string, 7
      optional :city, :string, 8
      optional :language, :string, 9
      repeated :subscribe_list, :string, 10
    end
    add_message "io.growing.tunnel.protocol.AliPayProfileDto" do
      optional :user_id, :string, 1
      optional :avatar, :string, 2
      optional :province, :string, 3
      optional :city, :string, 4
      optional :nick_name, :string, 5
      optional :is_student_certified, :bool, 6
      optional :user_type, :string, 7
      optional :user_status, :string, 8
      optional :is_certified, :bool, 9
      optional :gender, :string, 10
    end
  end
end

module Io
  module Growing
    module Tunnel
      module Protocol
        UserProfileDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.UserProfileDto").msgclass
        BasicProfileDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.BasicProfileDto").msgclass
        BasicProfileDto::Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.BasicProfileDto.Gender").enummodule
        DeviceProfileDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.DeviceProfileDto").msgclass
        WechatProfileDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.WechatProfileDto").msgclass
        AliPayProfileDto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.tunnel.protocol.AliPayProfileDto").msgclass
      end
    end
  end
end
