# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("messages.proto", :syntax => :proto3) do
    add_message "io.growing.vds.Event" do
      optional :ai, :string, 1
      optional :appid, :string, 2
      optional :uid, :int64, 3
      optional :csid, :int64, 4
      optional :ip, :string, 5
      optional :ua, :string, 6
      optional :u, :string, 7
      optional :s, :string, 8
      optional :t, :string, 9
      optional :tm, :int64, 10
      optional :ptm, :int64, 11
      optional :stm, :int64, 12
      optional :av, :string, 13
      optional :cv, :string, 14
      optional :d, :string, 15
      optional :p, :string, 16
      optional :q, :string, 17
      optional :ch, :string, 18
      optional :rf, :string, 19
      optional :rp, :string, 20
      optional :tl, :string, 21
      optional :n, :string, 22
      repeated :e, :message, 23, "io.growing.vds.Element"
      optional :db, :string, 24
      optional :dm, :string, 25
      optional :sh, :int32, 26
      optional :sw, :int32, 27
      optional :b, :string, 28
      optional :os, :string, 29
      optional :osv, :string, 30
      optional :l, :string, 31
      optional :cs1, :string, 32
      optional :lat, :float, 33
      optional :lng, :float, 34
      map :var, :string, :string, 35
      optional :esid, :int32, 36
      optional :geid, :int32, 37
      optional :ph, :int32, 38
      optional :sn, :string, 39
      optional :imei, :string, 40
      optional :adrid, :string, 41
      optional :num, :float, 42
      optional :o, :string, 43
      optional :iv, :string, 44
      optional :ui, :string, 45
    end
    add_message "io.growing.vds.Element" do
      optional :x, :string, 1
      optional :v, :string, 2
      optional :h, :string, 3
      optional :idx, :int32, 4
      optional :obj, :string, 5
      optional :tm, :int64, 6
      optional :gesid, :int32, 7
      optional :esid, :int32, 8
    end
    add_message "io.growing.vds.EventList" do
      repeated :values, :message, 1, "io.growing.vds.Event"
    end
  end
end

module Io
  module Growing
    module Vds
      Event = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.vds.Event").msgclass
      Element = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.vds.Element").msgclass
      EventList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.growing.vds.EventList").msgclass
    end
  end
end
